/**
 * One-time live-data patch: adds a per-word 🔊 audio button (speakWord)
 * next to each vocab word in Kenley's Vocabulary study-word tables
 * (v1, v2a, v3a, v4a, v5a), and removes the old whole-block "Read this
 * to me" instructional read-aloud from the app UI (that part is a code
 * change in app.js, not data — this script only updates the content_json
 * for the Vocabulary word tables, matching Setup.gs/Month1Weeks2to5.gs).
 *
 * Run once from the Apps Script editor. Safe to re-run.
 */
function fixVocabWordAudioButtons() {
  var NEW_CONTENT = {
  "v1": "<div class=\"lesson-text\"><p>Four words for this week, each tied to a root family you'll keep seeing:</p></div><table class=\"vocab-table\"><tr><td>incredulous <button class=\"btn word-audio-btn\" onclick=\"speakWord('incredulous')\">🔊</button></td><td>CRED- (believe) + IN-. Use it: describe a moment you were incredulous about something a sibling or friend told you.</td></tr><tr><td>deduction <button class=\"btn word-audio-btn\" onclick=\"speakWord('deduction')\">🔊</button></td><td>DUCT- (lead) + -TION. Use it: make a small deduction about something in the room right now, using only what you can observe.</td></tr><tr><td>meticulous <button class=\"btn word-audio-btn\" onclick=\"speakWord('meticulous')\">🔊</button></td><td>From Latin <i>metus</i> (fear) — \"fearful\" became \"extremely careful.\" Use it: describe a task that requires being meticulous.</td></tr><tr><td>resilient <button class=\"btn word-audio-btn\" onclick=\"speakWord('resilient')\">🔊</button></td><td>Latin <i>resilire</i>, \"to rebound.\" Use it: name someone or something resilient.</td></tr></table>",
  "v2a": "<div class=\"lesson-text\"><p>Five words this week, each used in a sentence that gives you a clue to its meaning. Notice <i>which part</i> of the sentence tips you off — a comma followed by a definition, a phrase that restates the word, or a contrast that shows the opposite.</p></div><table class=\"vocab-table\"><tr><td>rival <button class=\"btn word-audio-btn\" onclick=\"speakWord('rival')\">🔊</button></td><td>\"Martina Crowe was Reynie's rival, the one classmate who always tried to outdo him.\" (clue: comma-definition)</td></tr><tr><td>ominous <button class=\"btn word-audio-btn\" onclick=\"speakWord('ominous')\">🔊</button></td><td>\"The Waiting Room sounded ominous, threatening enough that even mentioning it made Sticky's hands shake.\" (clue: restating phrase)</td></tr><tr><td>irrational <button class=\"btn word-audio-btn\" onclick=\"speakWord('irrational')\">🔊</button></td><td>\"The anger Reynie felt was irrational — it made no sense, since nothing around him had actually changed.\" (clue: contrast)</td></tr><tr><td>perceptive <button class=\"btn word-audio-btn\" onclick=\"speakWord('perceptive')\">🔊</button></td><td>\"Unlike the others, Constance seemed unusually perceptive, noticing things no one else in the room could sense.\" (clue: contrast)</td></tr><tr><td>dismiss <button class=\"btn word-audio-btn\" onclick=\"speakWord('dismiss')\">🔊</button></td><td>\"Reynie wanted to dismiss the strange feeling, to brush it off and pretend he hadn't noticed it at all.\" (clue: restating phrase)</td></tr></table>",
  "v3a": "<div class=\"lesson-text\"><p>Five more words, each with a context clue built into the sentence. Watch for the same three clue types: comma-definition, contrast, or restating phrase.</p></div><table class=\"vocab-table\"><tr><td>deception <button class=\"btn word-audio-btn\" onclick=\"speakWord('deception')\">🔊</button></td><td>\"Lying to their teachers felt like deception, a kind of dishonesty that went against everything Reynie believed in.\" (clue: comma-definition)</td></tr><tr><td>reluctant <button class=\"btn word-audio-btn\" onclick=\"speakWord('reluctant')\">🔊</button></td><td>\"Sticky was reluctant to cheat, hesitating every time the plan required him to bend the rules.\" (clue: restating phrase)</td></tr><tr><td>camouflage <button class=\"btn word-audio-btn\" onclick=\"speakWord('camouflage')\">🔊</button></td><td>\"The trap blended into the forest like camouflage, disguised so well that only Kate's sharp eyes caught it.\" (clue: comma-definition)</td></tr><tr><td>complicit <button class=\"btn word-audio-btn\" onclick=\"speakWord('complicit')\">🔊</button></td><td>\"By staying silent, Reynie felt complicit — as guilty as if he'd caused the problem himself.\" (clue: restating phrase)</td></tr><tr><td>injustice <button class=\"btn word-audio-btn\" onclick=\"speakWord('injustice')\">🔊</button></td><td>\"Watching an innocent student take the blame felt like an injustice, an unfairness none of them could fix.\" (clue: comma-definition)</td></tr></table>",
  "v4a": "<div class=\"lesson-text\"><p>Five more words with context clues built in — this week’s theme is escalation and danger.</p></div><table class=\"vocab-table\"><tr><td>escalate <button class=\"btn word-audio-btn\" onclick=\"speakWord('escalate')\">🔊</button></td><td>\"Mr. Curtain didn't stop there — he continued to escalate the signal, making it stronger and harder to ignore.\" (clue: contrast)</td></tr><tr><td>vulnerable <button class=\"btn word-audio-btn\" onclick=\"speakWord('vulnerable')\">🔊</button></td><td>\"The stronger the messages became, the more vulnerable the children felt, as if anyone might crack under the pressure.\" (clue: restating phrase)</td></tr><tr><td>discreet <button class=\"btn word-audio-btn\" onclick=\"speakWord('discreet')\">🔊</button></td><td>\"Passing the note required them to be discreet, careful not to draw a single eye in their direction.\" (clue: comma-definition)</td></tr><tr><td>underestimate <button class=\"btn word-audio-btn\" onclick=\"speakWord('underestimate')\">🔊</button></td><td>\"It would have been easy to underestimate Constance, to assume the youngest and smallest member had nothing to offer.\" (clue: restating phrase)</td></tr><tr><td>resourceful <button class=\"btn word-audio-btn\" onclick=\"speakWord('resourceful')\">🔊</button></td><td>\"Time and again, the team relied on being resourceful, finding clever solutions with whatever they had on hand.\" (clue: comma-definition)</td></tr></table>",
  "v5a": "<div class=\"lesson-text\"><p>The last five words of Month 1 — escape, deception, payoff, and resolution, as the book wraps up.</p></div><table class=\"vocab-table\"><tr><td>resourcefulness <button class=\"btn word-audio-btn\" onclick=\"speakWord('resourcefulness')\">🔊</button></td><td>\"Kate's resourcefulness saved them — her knack for finding a tool or a trick out of almost nothing, even just a rope and a ladder.\" (clue: comma-definition)</td></tr><tr><td>futile <button class=\"btn word-audio-btn\" onclick=\"speakWord('futile')\">🔊</button></td><td>\"Reynie's attempt to fool the Whisperer was futile, a hopeless effort the machine saw through instantly.\" (clue: restating phrase)</td></tr><tr><td>vindicated <button class=\"btn word-audio-btn\" onclick=\"speakWord('vindicated')\">🔊</button></td><td>\"When Constance's stubbornness turned out to be exactly what saved them, Kate finally felt vindicated in trusting her all along.\" (clue: contextual/restating)</td></tr><tr><td>resolution <button class=\"btn word-audio-btn\" onclick=\"speakWord('resolution')\">🔊</button></td><td>\"The final chapter brought resolution to every storyline — each family reunited, each secret finally explained.\" (clue: comma-definition)</td></tr><tr><td>credible <button class=\"btn word-audio-btn\" onclick=\"speakWord('credible')\">🔊</button></td><td>\"Mr. Benedict's claims about Mr. Curtain finally became credible, believable enough that officials were willing to act.\" (clue: comma-definition/restating)</td></tr></table>"
  };
  var sh = getSheet_('Schedule');
  var values = sh.getDataRange().getValues();
  var headers = values[0];
  var studentCol = headers.indexOf('student');
  var taskCol = headers.indexOf('task_id');
  var contentCol = headers.indexOf('content_json');
  var fixed = [];

  for (var i = 1; i < values.length; i++) {
    var row = values[i];
    if (row[studentCol] !== 'kenley') continue;
    var taskId = row[taskCol];
    if (!NEW_CONTENT.hasOwnProperty(taskId)) continue;
    var existing = JSON.parse(row[contentCol] || '{}');
    existing.content = NEW_CONTENT[taskId];
    sh.getRange(i + 1, contentCol + 1).setValue(JSON.stringify(existing));
    fixed.push(taskId);
  }
  Logger.log('Updated content_json for: ' + fixed.join(', ') + ' (expected v1, v2a, v3a, v4a, v5a)');
}