/**
 * The ELA Pastry Kitchen — Month 1, Weeks 2–5 content (Kenley).
 *
 * Adds net-new Schedule rows for week_number 2–5, converted from
 * Month1_Weeks2-5_Grammar_Spelling_Writing.md and
 * Month1_Weeks2-5_Reading_Vocab.md into the same content_json shape used
 * for Week 1. Does NOT touch setupSheets() or any Week 1 rows — this is
 * purely additive.
 *
 * Run seedMonth1Weeks2to5_() ONCE from the function dropdown, after
 * setupSheets() has already been run at least once. It's idempotent: if
 * it detects task_id "g2a" already in the Schedule sheet, it assumes this
 * has already run and does nothing.
 *
 * Content notes (things Claude Code drafted itself rather than pulling
 * verbatim from your source docs, per your explicit go-ahead):
 *   - Spelling's four "This Week's Focus" rule explanations (Steps 8–11)
 *     are Claude's own write-up of the pattern, NOT sourced from the AAS
 *     teacher's manual the way Step 7's was. If you find the real manual
 *     text later, these are easy to swap — they're just plain content_json,
 *     no code depends on the exact wording.
 *   - Writing Week 2's "fresh Practice Set" (w2a) uses 3 new example pairs
 *     Claude wrote from scratch, modeled on Week 1's real Set A.
 *   - Grammar's per-word/per-phrase explanations for Weeks 2–5 are new
 *     text generated by substituting each week's words into Week 1's own
 *     explanation patterns (as the source doc asked for), not copied from
 *     anywhere else.
 *
 * Monthly/term-test tasks (s3/s4/s5, v3/v4, g8/g9, r4/r5) are NOT
 * duplicated per week — they already exist as single "unlocked whenever"
 * rows from Week 1 and keep working unchanged as new weeks are added.
 */

function seedMonth1Weeks2to5_() {
  var sh = getSheet_('Schedule');
  var existing = sheetToObjects_(sh);
  if (existing.some(function (r) { return r.task_id === 'g2a'; })) {
    SpreadsheetApp.getUi().alert('Weeks 2–5 content already appears to be seeded (found task g2a) — skipping to avoid duplicates.');
    return;
  }

  var rows = [];
  function addTasks(subjectKey, subjectName, subjectTag, weekNumber, tasks) {
    tasks.forEach(function (t) {
      var content = {};
      Object.keys(t).forEach(function (k) {
        if (['id', 'label', 'type', 'dynamic', 'termFinal', 'monthlyTest'].indexOf(k) === -1) content[k] = t[k];
      });
      rows.push([
        'kenley', subjectKey, subjectName, subjectTag, weekNumber,
        t.id, t.type, t.label, JSON.stringify(content),
        t.dynamic || '', !!t.termFinal, !!t.monthlyTest
      ]);
    });
  }

  MONTH1_WEEKS_2_TO_5.forEach(function (week) {
    Object.keys(week.subjects).forEach(function (subjectKey) {
      var subj = week.subjects[subjectKey];
      addTasks(subjectKey, subj.name, subj.tag, week.week_number, subj.tasks);
    });
  });

  var headers = SHEET_HEADERS.Schedule;
  sh.getRange(sh.getLastRow() + 1, 1, rows.length, headers.length).setValues(rows);
  SpreadsheetApp.getUi().alert('Added ' + rows.length + ' new Schedule rows for Kenley, Weeks 2–5.');
}

// ---------- Content ----------

var MONTH1_WEEKS_2_TO_5 = [
  // ================= WEEK 2 =================
  {
    week_number: 2,
    subjects: {
      vocab: {
        name: 'Vocabulary', tag: 'Context Clues · Month 1',
        tasks: [
          { id: 'v2a', label: "Study This Week's Words", type: 'read', content:
            '<div class="lesson-text"><p>Five words this week, each used in a sentence that gives you a clue to its meaning. Notice <i>which part</i> of the sentence tips you off — a comma followed by a definition, a phrase that restates the word, or a contrast that shows the opposite.</p></div>' +
            '<table class="vocab-table">' +
            '<tr><td>rival</td><td>"Martina Crowe was Reynie\'s rival, the one classmate who always tried to outdo him." (clue: comma-definition)</td></tr>' +
            '<tr><td>ominous</td><td>"The Waiting Room sounded ominous, threatening enough that even mentioning it made Sticky\'s hands shake." (clue: restating phrase)</td></tr>' +
            '<tr><td>irrational</td><td>"The anger Reynie felt was irrational — it made no sense, since nothing around him had actually changed." (clue: contrast)</td></tr>' +
            '<tr><td>perceptive</td><td>"Unlike the others, Constance seemed unusually perceptive, noticing things no one else in the room could sense." (clue: contrast)</td></tr>' +
            '<tr><td>dismiss</td><td>"Reynie wanted to dismiss the strange feeling, to brush it off and pretend he hadn\'t noticed it at all." (clue: restating phrase)</td></tr>' +
            '</table>' },
          { id: 'v2b', label: 'Which Clue Told You the Meaning?', type: 'reflection',
            prompt: 'Pick at least two of this week\'s words (rival, ominous, irrational, perceptive, dismiss) and explain what specific part of the sentence gave away its meaning — was it a comma-definition, a contrast, or a restating phrase? Naming the word alone isn\'t enough; point to the actual words in the sentence that tipped you off.' }
        ]
      },
      grammar: {
        name: 'Grammar', tag: 'MCT-Based · Month 1, Week 2 Review',
        tasks: [
          { id: 'g2a', label: 'Level 1 — Tag the Parts of Speech', type: 'pos-tagger',
            sentence: ['Although', 'the', 'wizard', 'seemed', 'exhausted,', 'Pickles,', 'the', 'ridiculous', 'parrot,', 'devoured', 'an', 'entire', 'pizza', 'during', 'the', 'movie.'],
            answers: ['Conjunction', 'Adjective', 'Noun', 'Verb', 'Adjective', 'Noun', 'Adjective', 'Adjective', 'Noun', 'Verb', 'Adjective', 'Adjective', 'Noun', 'Preposition', 'Adjective', 'Noun'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.pos,
            explanations: [
              '"Although" introduces the dependent clause and connects it to the main clause — that\'s a conjunction\'s job.',
              'Articles (a, an, the) are treated as adjectives — they modify the noun that follows.',
              'It names a thing — nouns name people, places, things, or ideas.',
              'It shows what the subject "wizard" is described as. We\'ll classify it as action or linking specifically in Level 2.',
              'It describes "wizard" — adjectives describe nouns.',
              'It names a specific individual — a proper noun.',
              'Article.',
              'It describes "parrot," — adjectives describe nouns.',
              'It names an animal — a renamed identity for Pickles.',
              'It shows the action the subject performed.',
              'Article.',
              'It describes "pizza" — adjectives describe nouns.',
              'It names a thing — the object of the action.',
              'It introduces a phrase showing where something happened, connecting to its object, "movie."',
              'Article.',
              'It names a thing — the object of the preposition "during."'
            ] },
          { id: 'g2b', label: 'Level 2 — Tag the Parts of the Sentence', type: 'phrase-tagger',
            sentence: ['Although', 'the', 'wizard', 'seemed', 'exhausted,', 'Pickles,', 'the', 'ridiculous', 'parrot,', 'devoured', 'an', 'entire', 'pizza', 'during', 'the', 'movie.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.sentence,
            phrases: [
              { start: 2, end: 2, type: 'Subject', explanation: '"Wizard" is who/what the dependent clause is about.' },
              { start: 3, end: 3, type: 'Linking Verb Predicate', explanation: '"Seemed" doesn\'t show an action — it links "wizard" to a description. That makes it a linking verb predicate, not an action verb predicate.' },
              { start: 4, end: 4, type: 'Subject Complement', explanation: '"Exhausted" describes the subject "wizard" after the linking verb "seemed" — that\'s exactly what a subject complement does.' },
              { start: 5, end: 5, type: 'Subject', explanation: '"Pickles" is who the main clause is about — the one doing the action.' },
              { start: 9, end: 9, type: 'Action Verb Predicate', explanation: '"Devoured" shows a real action Pickles performed, and it takes a direct object — only action verbs can do that.' },
              { start: 10, end: 12, type: 'Direct Object', explanation: '"An entire pizza" is what got devoured — the direct object answers "what."' }
            ] },
          { id: 'g2c', label: 'Level 3 — Mark the Phrases', type: 'phrase-tagger',
            sentence: ['Although', 'the', 'wizard', 'seemed', 'exhausted,', 'Pickles,', 'the', 'ridiculous', 'parrot,', 'devoured', 'an', 'entire', 'pizza', 'during', 'the', 'movie.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.phrase,
            phrases: [
              { start: 6, end: 8, type: 'Appositive', explanation: 'It renames "Pickles" — telling you who Pickles is, not where or when anything happened, which is what makes it an appositive instead of prepositional.' },
              { start: 13, end: 15, type: 'Prepositional', explanation: 'It starts with the preposition "during" and ends with its object "movie" — that\'s the exact shape of a prepositional phrase.' }
            ] },
          { id: 'g2d', label: 'Level 4 — Mark the Clauses', type: 'phrase-tagger',
            sentence: ['Although', 'the', 'wizard', 'seemed', 'exhausted,', 'Pickles,', 'the', 'ridiculous', 'parrot,', 'devoured', 'an', 'entire', 'pizza', 'during', 'the', 'movie.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.clause,
            phrases: [
              { start: 0, end: 4, type: 'Dependent Clause', explanation: 'It starts with the subordinating conjunction "although" and can\'t stand alone as a complete sentence — that makes it dependent.' },
              { start: 5, end: 15, type: 'Independent Clause', explanation: 'It has its own subject and predicate ("Pickles... devoured...") and could stand alone as a complete sentence — that makes it independent.' }
            ] },
          { id: 'g2e', label: 'Level 4 — Classify the Sentence Structure', type: 'graded-mc',
            questions: [
              { q: '"Although the wizard seemed exhausted, Pickles, the ridiculous parrot, devoured an entire pizza during the movie." — one independent clause plus one dependent clause makes this sentence:', options: GRAMMAR_LEVEL_OPTIONS_SEED.structure, correct: 2,
                explanation: 'One independent clause + one dependent clause = complex. (Simple = one independent clause alone. Compound = two or more independent clauses joined. Compound-complex = two+ independent clauses plus at least one dependent clause.)' }
            ] }
        ]
      },
      spelling: {
        name: 'Spelling', tag: 'AAS Level 7 · Step 8',
        tasks: [
          { id: 's2a', label: "This Week's Focus", type: 'read', content:
            '<div class="lesson-text"><p><b>Step 8 — Some Consonant Suffixes Still Drop the Silent E.</b> Normally, when a word ends in a silent e and you add a suffix that starts with a consonant, you keep the e (care + ful = careful). This step’s words are the exceptions: judge → judgment, acknowledge → acknowledgment, argue → argument, true → truly, whole → wholly, and awe → awful all drop that silent e anyway, even though the suffix starts with a consonant.</p><p>A few of this week’s other words — ninth, wisdom, wherever — don’t follow that exact drop-e pattern; they’re simply this step’s other words to know by sight.</p><p><b>New homophone-style note: wholly.</b> "I am wholly convinced of the truth." Watch the spelling carefully — it’s easy to drop a letter.</p></div>' },
          { id: 's2b', label: 'Word Cards 61–70 dictation', type: 'graded-dictation',
            prompt: 'Tap ▶ to hear each word — no text shown, same as Mom reading from the card.',
            words: [
              { answer: 'judgment', kind: 'word' }, { answer: 'acknowledgment', kind: 'word' }, { answer: 'gently', kind: 'word' },
              { answer: 'argument', kind: 'word' }, { answer: 'awful', kind: 'word' }, { answer: 'truly', kind: 'word' },
              { answer: 'ninth', kind: 'word' }, { answer: 'wholly', kind: 'word', context: 'I am wholly convinced of the truth.' },
              { answer: 'wisdom', kind: 'word' }, { answer: 'wherever', kind: 'word' }
            ] },
          { id: 's2c', label: 'Dictated sentences', type: 'graded-dictation',
            prompt: "This week's sentences each pair a new Step 8 word with an older review word, so dictation doubles as retrieval practice.",
            words: [
              { answer: "Even though it wasn't her job, Mom used her best judgment and shared her opinion anyway.", kind: 'sentence' },
              { answer: "I could hardly believe the letter's simple acknowledgment of her hard work.", kind: 'sentence' },
              { answer: "She gently peeled the onion so it wouldn't make her cry.", kind: 'sentence' },
              { answer: 'Their argument started the moment the two sisters began to disagree about the movie.', kind: 'sentence' },
              { answer: "Even the harshest critics wouldn't condemn such an awful pun.", kind: 'sentence' },
              { answer: "I truly hope we can keep the twins' backpacks separate this time.", kind: 'sentence' },
              { answer: 'By the ninth day of autumn, the leaves had already turned gold.', kind: 'sentence' },
              { answer: 'Though he seemed unsure at first, Dad was wholly convinced of the plan by dinner.', kind: 'sentence' },
              { answer: "My grandmother's endless wisdom made her the best companion for a long road trip.", kind: 'sentence' },
              { answer: "Wherever the two rivers meet, there's a strange union of clear water and muddy water.", kind: 'sentence' }
            ] }
        ]
      },
      reading: {
        name: 'Reading', tag: 'The Mysterious Benedict Society · Ch. 9–16',
        tasks: [
          { id: 'r2a', label: 'This Week’s Reading: Chapters 9–16', type: 'read', content:
            '<div class="lesson-text"><p><b>As you read, watch for:</b></p><p>1. How each of the four kids reacts differently to their rival classmate, Martina Crowe. Notice what each reaction reveals about that character.</p><p>2. The "Waiting Room" punishment. Notice we’re never actually told what happens inside it — only how kids act afterward. That withheld information is the Plot Structure lens at work again.</p><p>3. Near the end of this range, watch for a moment where all four kids suddenly feel a strong, confusing emotion. Notice that Reynie has to <i>guess</i> what’s happening to himself and his friends in real time — nothing gets explained to him first.</p></div>' },
          { id: 'r2b', label: 'Discussion — Plot Structure', type: 'reflection',
            prompt: "When the group suddenly feels a strange emotion they can't explain, we only find out what's happening through Reynie noticing his own reaction and guessing at his friends'. Why might the author choose to have us discover this the same confused way Reynie does, instead of just explaining it to us upfront?" },
          { id: 'r2c', label: 'Discussion — POV / Foreshadowing', type: 'reflection',
            prompt: 'One character reacts differently than the others to what’s happening to the group. What might that difference be hinting will matter later?' }
        ]
      },
      writing: {
        name: 'Writing', tag: 'MCT Essay Voyage (adapted) · Block 1',
        tasks: [
          { id: 'w2a', label: 'Practice Set B — Vague or Specific?', type: 'graded-mc',
            questions: [
              { q: 'Which is real evidence? A) "Video games are a waste of time because they’re not productive." B) "In a 2020 study, kids who played strategy games for 30 minutes a day scored higher on problem-solving tests than kids who didn’t."', options: ['A', 'B'], correct: 1 },
              { q: 'Which is real evidence? A) "Our team’s win record improved from 3-9 to 9-3 after we started practicing twice a week instead of once." B) "Practicing more just makes a team better overall."', options: ['A', 'B'], correct: 0 },
              { q: 'Which of these is a fact rather than an opinion?', options: ['"Reading before bed is the best way to relax."', '"A 2018 survey found that 68% of people who read before bed reported falling asleep faster."'], correct: 1 }
            ] },
          { id: 'w2b', label: 'Draft a New Free-Topic Argument', type: 'reflection',
            prompt: 'Pick a different real opinion you hold than the one you used before (or a new angle on the same one). Write your draft paragraph — claim, evidence, explain — then apply the specificity test and the fact-vs-opinion check to your evidence before you’re done.' }
        ]
      }
    }
  },

  // ================= WEEK 3 =================
  {
    week_number: 3,
    subjects: {
      vocab: {
        name: 'Vocabulary', tag: 'Context Clues · Month 1',
        tasks: [
          { id: 'v3a', label: "Study This Week's Words", type: 'read', content:
            '<div class="lesson-text"><p>Five more words, each with a context clue built into the sentence. Watch for the same three clue types: comma-definition, contrast, or restating phrase.</p></div>' +
            '<table class="vocab-table">' +
            '<tr><td>deception</td><td>"Lying to their teachers felt like deception, a kind of dishonesty that went against everything Reynie believed in." (clue: comma-definition)</td></tr>' +
            '<tr><td>reluctant</td><td>"Sticky was reluctant to cheat, hesitating every time the plan required him to bend the rules." (clue: restating phrase)</td></tr>' +
            '<tr><td>camouflage</td><td>"The trap blended into the forest like camouflage, disguised so well that only Kate\'s sharp eyes caught it." (clue: comma-definition)</td></tr>' +
            '<tr><td>complicit</td><td>"By staying silent, Reynie felt complicit — as guilty as if he\'d caused the problem himself." (clue: restating phrase)</td></tr>' +
            '<tr><td>injustice</td><td>"Watching an innocent student take the blame felt like an injustice, an unfairness none of them could fix." (clue: comma-definition)</td></tr>' +
            '</table>' },
          { id: 'v3b', label: 'Which Clue Told You the Meaning?', type: 'reflection',
            prompt: 'Pick at least two of this week\'s words (deception, reluctant, camouflage, complicit, injustice) and explain what specific part of the sentence gave away its meaning. Point to the actual words that tipped you off, not just a definition.' }
        ]
      },
      grammar: {
        name: 'Grammar', tag: 'MCT-Based · Month 1, Week 3 Review',
        tasks: [
          { id: 'g3a', label: 'Level 1 — Tag the Parts of Speech', type: 'pos-tagger',
            sentence: ['Because', 'the', 'soup', 'tasted', 'disgusting,', 'Waffles,', 'the', 'overconfident', 'chef,', 'dumped', 'the', 'entire', 'pot', 'into', 'the', 'garden.'],
            answers: ['Conjunction', 'Adjective', 'Noun', 'Verb', 'Adjective', 'Noun', 'Adjective', 'Adjective', 'Noun', 'Verb', 'Adjective', 'Adjective', 'Noun', 'Preposition', 'Adjective', 'Noun'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.pos,
            explanations: [
              '"Because" introduces the dependent clause and connects it to the main clause — that\'s a conjunction\'s job.',
              'Articles (a, an, the) are treated as adjectives — they modify the noun that follows.',
              'It names a thing — nouns name people, places, things, or ideas.',
              'It shows what the subject "soup" is described as. We\'ll classify it as action or linking specifically in Level 2.',
              'It describes "soup" — adjectives describe nouns.',
              'It names a specific individual — a proper noun.',
              'Article.',
              'It describes "chef," — adjectives describe nouns.',
              'It names a person — a renamed identity for Waffles.',
              'It shows the action the subject performed.',
              'Article.',
              'It describes "pot" — adjectives describe nouns.',
              'It names a thing — the object of the action.',
              'It introduces a phrase showing where something happened, connecting to its object, "garden."',
              'Article.',
              'It names a place — the object of the preposition "into."'
            ] },
          { id: 'g3b', label: 'Level 2 — Tag the Parts of the Sentence', type: 'phrase-tagger',
            sentence: ['Because', 'the', 'soup', 'tasted', 'disgusting,', 'Waffles,', 'the', 'overconfident', 'chef,', 'dumped', 'the', 'entire', 'pot', 'into', 'the', 'garden.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.sentence,
            phrases: [
              { start: 2, end: 2, type: 'Subject', explanation: '"Soup" is who/what the dependent clause is about.' },
              { start: 3, end: 3, type: 'Linking Verb Predicate', explanation: '"Tasted" doesn\'t show an action — it links "soup" to a description. That makes it a linking verb predicate, not an action verb predicate.' },
              { start: 4, end: 4, type: 'Subject Complement', explanation: '"Disgusting" describes the subject "soup" after the linking verb "tasted" — that\'s exactly what a subject complement does.' },
              { start: 5, end: 5, type: 'Subject', explanation: '"Waffles" is who the main clause is about — the one doing the action.' },
              { start: 9, end: 9, type: 'Action Verb Predicate', explanation: '"Dumped" shows a real action Waffles performed, and it takes a direct object — only action verbs can do that.' },
              { start: 10, end: 12, type: 'Direct Object', explanation: '"The entire pot" is what got dumped — the direct object answers "what."' }
            ] },
          { id: 'g3c', label: 'Level 3 — Mark the Phrases', type: 'phrase-tagger',
            sentence: ['Because', 'the', 'soup', 'tasted', 'disgusting,', 'Waffles,', 'the', 'overconfident', 'chef,', 'dumped', 'the', 'entire', 'pot', 'into', 'the', 'garden.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.phrase,
            phrases: [
              { start: 6, end: 8, type: 'Appositive', explanation: 'It renames "Waffles" — telling you who Waffles is, not where or when anything happened, which is what makes it an appositive instead of prepositional.' },
              { start: 13, end: 15, type: 'Prepositional', explanation: 'It starts with the preposition "into" and ends with its object "garden" — that\'s the exact shape of a prepositional phrase.' }
            ] },
          { id: 'g3d', label: 'Level 4 — Mark the Clauses', type: 'phrase-tagger',
            sentence: ['Because', 'the', 'soup', 'tasted', 'disgusting,', 'Waffles,', 'the', 'overconfident', 'chef,', 'dumped', 'the', 'entire', 'pot', 'into', 'the', 'garden.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.clause,
            phrases: [
              { start: 0, end: 4, type: 'Dependent Clause', explanation: 'It starts with the subordinating conjunction "because" and can\'t stand alone as a complete sentence — that makes it dependent.' },
              { start: 5, end: 15, type: 'Independent Clause', explanation: 'It has its own subject and predicate ("Waffles... dumped...") and could stand alone as a complete sentence — that makes it independent.' }
            ] },
          { id: 'g3e', label: 'Level 4 — Classify the Sentence Structure', type: 'graded-mc',
            questions: [
              { q: '"Because the soup tasted disgusting, Waffles, the overconfident chef, dumped the entire pot into the garden." — one independent clause plus one dependent clause makes this sentence:', options: GRAMMAR_LEVEL_OPTIONS_SEED.structure, correct: 2,
                explanation: 'One independent clause + one dependent clause = complex. (Simple = one independent clause alone. Compound = two or more independent clauses joined. Compound-complex = two+ independent clauses plus at least one dependent clause.)' }
            ] }
        ]
      },
      spelling: {
        name: 'Spelling', tag: 'AAS Level 7 · Step 9',
        tasks: [
          { id: 's3a', label: "This Week's Focus", type: 'read', content:
            '<div class="lesson-text"><p><b>Step 9 — Keep the E to Keep C and G Soft.</b> Normally, you drop a silent final e before a suffix that starts with a vowel (move + ing = moving). But when a word ends in a <i>soft</i> c (sounds like /s/) or <i>soft</i> g (sounds like /j/), you keep that e — otherwise the c or g would harden.</p><p>Courage ends with a soft g, so courage + ous = courageous, not "courags." Notice ends with a soft c, so notice + able = noticeable, not "noticable." This week’s words — courageous, changeable, noticeable, rechargeable, irreplaceable, knowledgeable, outrageous, manageable, gorgeous, traceable — all keep their e for exactly this reason.</p></div>' },
          { id: 's3b', label: 'Word Cards 71–80 dictation', type: 'graded-dictation',
            prompt: 'Tap ▶ to hear each word — no text shown, same as Mom reading from the card.',
            words: [
              { answer: 'courageous', kind: 'word' }, { answer: 'changeable', kind: 'word' }, { answer: 'noticeable', kind: 'word' },
              { answer: 'rechargeable', kind: 'word' }, { answer: 'irreplaceable', kind: 'word' }, { answer: 'gorgeous', kind: 'word' },
              { answer: 'knowledgeable', kind: 'word' }, { answer: 'outrageous', kind: 'word' }, { answer: 'manageable', kind: 'word' }, { answer: 'traceable', kind: 'word' }
            ] },
          { id: 's3c', label: 'Dictated sentences', type: 'graded-dictation',
            prompt: "All 10 sentences from this week's Reinforcement section.",
            words: [
              { answer: "Don't worry! The mustard on your tie is hardly noticeable!", kind: 'sentence' },
              { answer: 'The weather at sea is dangerously changeable.', kind: 'sentence' },
              { answer: 'Ed offered his knowledgeable opinions on whales.', kind: 'sentence' },
              { answer: 'All of our nature designs are traceable.', kind: 'sentence' },
              { answer: 'The smile of a happy child is an irreplaceable gift.', kind: 'sentence' },
              { answer: 'Sam sells his gorgeous soap carvings at street fairs.', kind: 'sentence' },
              { answer: 'The courageous farmer promised to save all the cows.', kind: 'sentence' },
              { answer: "Let's break the problem down into manageable parts.", kind: 'sentence' },
              { answer: 'She invented a rechargeable sandwich warmer.', kind: 'sentence' },
              { answer: 'Those giggling geese are simply outrageous!', kind: 'sentence' }
            ] }
        ]
      },
      reading: {
        name: 'Reading', tag: 'The Mysterious Benedict Society · Ch. 17–24',
        tasks: [
          { id: 'r3a', label: 'This Week’s Reading: Chapters 17–24', type: 'read', content:
            '<div class="lesson-text"><p><b>As you read, watch for:</b></p><p>1. Reynie’s growing discomfort with lying and cheating in order to move up in rank. Notice this is an internal conflict we only know about because we’re inside his head.</p><p>2. A scene where all four kids use a different personal strength to solve the same small problem. Notice how the author uses this to remind you who each character is, without stating it outright.</p><p>3. A moment where the mission’s cost becomes real — where someone innocent ends up taking the blame for something the team caused.</p></div>' },
          { id: 'r3b', label: 'Discussion — POV', type: 'reflection',
            prompt: "We know about Reynie's discomfort with deception because we're inside his head, not because anyone tells us. If this story were narrated by Sticky or Kate instead, do you think we'd feel that same discomfort as strongly? Why or why not?" },
          { id: 'r3c', label: 'Discussion — Plot Structure', type: 'reflection',
            prompt: "An innocent person ends up taking the blame for something the team did. Why might the author give the kids' success a real cost to someone else, instead of making the mission easy and consequence-free?" }
        ]
      },
      writing: {
        name: 'Writing', tag: 'MCT Essay Voyage (adapted) · Block 1',
        tasks: [
          { id: 'w3a', label: 'Expand to Two Connected Paragraphs', type: 'reflection',
            prompt: 'Pull up the paragraph you wrote last week. Add a second claim-evidence-explain paragraph that supports the SAME overall argument — don’t start a new topic. When you’re done, check: does your new evidence pass the specificity test and the fact-vs-opinion test? And do the two paragraphs actually work together as one argument, or do they feel like two separate ones?' }
        ]
      }
    }
  },

  // ================= WEEK 4 =================
  {
    week_number: 4,
    subjects: {
      vocab: {
        name: 'Vocabulary', tag: 'Context Clues · Month 1',
        tasks: [
          { id: 'v4a', label: "Study This Week's Words", type: 'read', content:
            '<div class="lesson-text"><p>Five more words with context clues built in — this week’s theme is escalation and danger.</p></div>' +
            '<table class="vocab-table">' +
            '<tr><td>escalate</td><td>"Mr. Curtain didn\'t stop there — he continued to escalate the signal, making it stronger and harder to ignore." (clue: contrast)</td></tr>' +
            '<tr><td>vulnerable</td><td>"The stronger the messages became, the more vulnerable the children felt, as if anyone might crack under the pressure." (clue: restating phrase)</td></tr>' +
            '<tr><td>discreet</td><td>"Passing the note required them to be discreet, careful not to draw a single eye in their direction." (clue: comma-definition)</td></tr>' +
            '<tr><td>underestimate</td><td>"It would have been easy to underestimate Constance, to assume the youngest and smallest member had nothing to offer." (clue: restating phrase)</td></tr>' +
            '<tr><td>resourceful</td><td>"Time and again, the team relied on being resourceful, finding clever solutions with whatever they had on hand." (clue: comma-definition)</td></tr>' +
            '</table>' },
          { id: 'v4b', label: 'Which Clue Told You the Meaning?', type: 'reflection',
            prompt: 'Pick at least two of this week\'s words (escalate, vulnerable, discreet, underestimate, resourceful) and explain what specific part of the sentence gave away its meaning. Point to the actual words that tipped you off, not just a definition.' }
        ]
      },
      grammar: {
        name: 'Grammar', tag: 'MCT-Based · Month 1, Week 4 Review',
        tasks: [
          { id: 'g4a', label: 'Level 1 — Tag the Parts of Speech', type: 'pos-tagger',
            sentence: ['Since', 'the', 'referee', 'looked', 'furious,', 'Bruno,', 'the', 'clumsiest', 'player,', 'launched', 'the', 'ball', 'straight', 'through', 'the', 'window.'],
            answers: ['Conjunction', 'Adjective', 'Noun', 'Verb', 'Adjective', 'Noun', 'Adjective', 'Adjective', 'Noun', 'Verb', 'Adjective', 'Noun', 'Adverb', 'Preposition', 'Adjective', 'Noun'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.pos,
            explanations: [
              '"Since" introduces the dependent clause and connects it to the main clause — that\'s a conjunction\'s job.',
              'Articles (a, an, the) are treated as adjectives — they modify the noun that follows.',
              'It names a thing — nouns name people, places, things, or ideas.',
              'It shows what the subject "referee" is described as. We\'ll classify it as action or linking specifically in Level 2.',
              'It describes "referee" — adjectives describe nouns.',
              'It names a specific individual — a proper noun.',
              'Article.',
              'It describes "player," comparing degree — "clumsiest" is a superlative adjective.',
              'It names a person — a renamed identity for Bruno.',
              'It shows the action the subject performed.',
              'Article.',
              'It names a thing — the object of the action.',
              'It describes how "launched" happened — adverbs describe verbs, not nouns. (Bonus word — this is the only adverb this month!)',
              'It introduces a phrase showing where something happened, connecting to its object, "window."',
              'Article.',
              'It names a place — the object of the preposition "through."'
            ] },
          { id: 'g4b', label: 'Level 2 — Tag the Parts of the Sentence', type: 'phrase-tagger',
            sentence: ['Since', 'the', 'referee', 'looked', 'furious,', 'Bruno,', 'the', 'clumsiest', 'player,', 'launched', 'the', 'ball', 'straight', 'through', 'the', 'window.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.sentence,
            phrases: [
              { start: 2, end: 2, type: 'Subject', explanation: '"Referee" is who/what the dependent clause is about.' },
              { start: 3, end: 3, type: 'Linking Verb Predicate', explanation: '"Looked" doesn\'t show an action — it links "referee" to a description. That makes it a linking verb predicate, not an action verb predicate.' },
              { start: 4, end: 4, type: 'Subject Complement', explanation: '"Furious" describes the subject "referee" after the linking verb "looked" — that\'s exactly what a subject complement does.' },
              { start: 5, end: 5, type: 'Subject', explanation: '"Bruno" is who the main clause is about — the one doing the action.' },
              { start: 9, end: 9, type: 'Action Verb Predicate', explanation: '"Launched" shows a real action Bruno performed, and it takes a direct object — only action verbs can do that.' },
              { start: 10, end: 11, type: 'Direct Object', explanation: '"The ball" is what got launched — the direct object answers "what."' }
            ] },
          { id: 'g4c', label: 'Level 3 — Mark the Phrases', type: 'phrase-tagger',
            sentence: ['Since', 'the', 'referee', 'looked', 'furious,', 'Bruno,', 'the', 'clumsiest', 'player,', 'launched', 'the', 'ball', 'straight', 'through', 'the', 'window.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.phrase,
            phrases: [
              { start: 6, end: 8, type: 'Appositive', explanation: 'It renames "Bruno" — telling you who Bruno is, not where or when anything happened, which is what makes it an appositive instead of prepositional.' },
              { start: 13, end: 15, type: 'Prepositional', explanation: 'It starts with the preposition "through" and ends with its object "window" — that\'s the exact shape of a prepositional phrase.' }
            ] },
          { id: 'g4d', label: 'Level 4 — Mark the Clauses', type: 'phrase-tagger',
            sentence: ['Since', 'the', 'referee', 'looked', 'furious,', 'Bruno,', 'the', 'clumsiest', 'player,', 'launched', 'the', 'ball', 'straight', 'through', 'the', 'window.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.clause,
            phrases: [
              { start: 0, end: 4, type: 'Dependent Clause', explanation: 'It starts with the subordinating conjunction "since" and can\'t stand alone as a complete sentence — that makes it dependent.' },
              { start: 5, end: 15, type: 'Independent Clause', explanation: 'It has its own subject and predicate ("Bruno... launched...") and could stand alone as a complete sentence — that makes it independent.' }
            ] },
          { id: 'g4e', label: 'Level 4 — Classify the Sentence Structure', type: 'graded-mc',
            questions: [
              { q: '"Since the referee looked furious, Bruno, the clumsiest player, launched the ball straight through the window." — one independent clause plus one dependent clause makes this sentence:', options: GRAMMAR_LEVEL_OPTIONS_SEED.structure, correct: 2,
                explanation: 'One independent clause + one dependent clause = complex. (Simple = one independent clause alone. Compound = two or more independent clauses joined. Compound-complex = two+ independent clauses plus at least one dependent clause.)' }
            ] }
        ]
      },
      spelling: {
        name: 'Spelling', tag: 'AAS Level 7 · Step 10',
        tasks: [
          { id: 's4a', label: "This Week's Focus", type: 'read', content:
            '<div class="lesson-text"><p><b>Step 10 — The /sh/ Sound Spelled CI.</b> You already know /sh/ can be spelled <u>sh</u> (ship) or <u>ti</u> (nation). This step adds one more spelling: <u>ci</u>, usually right before another vowel — official, special, artificial, delicious, musician, electrician, pediatrician, ancient, efficient, appreciate.</p><p>Say each word slowly and listen for the /sh/ sound hiding inside the letters c-i.</p></div>' },
          { id: 's4b', label: 'Word Cards 81–90 dictation', type: 'graded-dictation',
            prompt: 'Tap ▶ to hear each word — no text shown, same as Mom reading from the card.',
            words: [
              { answer: 'official', kind: 'word' }, { answer: 'special', kind: 'word' }, { answer: 'artificial', kind: 'word' },
              { answer: 'delicious', kind: 'word' }, { answer: 'musician', kind: 'word' }, { answer: 'electrician', kind: 'word' },
              { answer: 'pediatrician', kind: 'word' }, { answer: 'ancient', kind: 'word' }, { answer: 'efficient', kind: 'word' }, { answer: 'appreciate', kind: 'word' }
            ] },
          { id: 's4c', label: 'Dictated sentences', type: 'graded-dictation',
            prompt: "All 10 sentences from this week's Reinforcement section.",
            words: [
              { answer: 'The pediatrician said that Dan should eat less fruitcake.', kind: 'sentence' },
              { answer: 'Did you call the electrician to fix the washing machine?', kind: 'sentence' },
              { answer: 'We visited eleven ancient cities on our trip to India.', kind: 'sentence' },
              { answer: 'The gerbils enjoyed a delicious lunch of seeds and grass.', kind: 'sentence' },
              { answer: "Let's schedule a musician for the ninth of August.", kind: 'sentence' },
              { answer: "Aunt Sue's artificial trees never lose their leaves in autumn.", kind: 'sentence' },
              { answer: 'I made my special vanilla cupcakes for the occasion.', kind: 'sentence' },
              { answer: 'We signed the official contract three days ago.', kind: 'sentence' },
              { answer: 'My daughters appreciate the box of chocolates you sent.', kind: 'sentence' },
              { answer: 'The toothless shark was not very efficient at catching his dinner.', kind: 'sentence' }
            ] }
        ]
      },
      reading: {
        name: 'Reading', tag: 'The Mysterious Benedict Society · Ch. 25–32',
        tasks: [
          { id: 'r4a', label: 'This Week’s Reading: Chapters 25–32', type: 'read', content:
            '<div class="lesson-text"><p><b>As you read, watch for:</b></p><p>1. As the hidden messages get stronger, notice that each character reacts a little differently — especially Constance.</p><p>2. A near-disaster scene where the team is almost caught. Notice the tension is built through small physical details (who’s watching, what’s being passed between people) rather than the author just telling you "they almost got caught."</p><p>3. Notice how much the team ends up depending on the character who seemed the least capable at the start of the book.</p></div>' },
          { id: 'r4b', label: 'Discussion — Plot Structure', type: 'reflection',
            prompt: 'The author builds a near-miss scene using a lot of small physical details rather than just summarizing "they almost got caught." Why might slowing time down like that during a tense moment work better than rushing through it?' },
          { id: 'r4c', label: 'Discussion — POV / Characterization', type: 'reflection',
            prompt: "A character who seemed 'weakest' early on turns out to matter enormously by this point. Since we only see her through Reynie's POV, has our understanding of her changed because she changed — or because Reynie is finally noticing something that was true all along?" }
        ]
      },
      writing: {
        name: 'Writing', tag: 'MCT Essay Voyage (adapted) · Block 1',
        tasks: [
          { id: 'w4a', label: 'Revision Pass', type: 'reflection',
            prompt: 'Pull up your Week 2 or Week 3 draft. Go through every piece of evidence you used and re-run both tests: the specificity test (could this evidence be swapped into a totally different essay and still fit?) and the fact-vs-opinion test (is it actually checkable, not just another opinion in disguise?). Revise anything that fails, then paste your revised version here.' }
        ]
      }
    }
  },

  // ================= WEEK 5 =================
  {
    week_number: 5,
    subjects: {
      vocab: {
        name: 'Vocabulary', tag: 'Context Clues · Month 1',
        tasks: [
          { id: 'v5a', label: "Study This Week's Words", type: 'read', content:
            '<div class="lesson-text"><p>The last five words of Month 1 — escape, deception, payoff, and resolution, as the book wraps up.</p></div>' +
            '<table class="vocab-table">' +
            '<tr><td>resourcefulness</td><td>"Kate\'s resourcefulness saved them — her knack for finding a tool or a trick out of almost nothing, even just a rope and a ladder." (clue: comma-definition)</td></tr>' +
            '<tr><td>futile</td><td>"Reynie\'s attempt to fool the Whisperer was futile, a hopeless effort the machine saw through instantly." (clue: restating phrase)</td></tr>' +
            '<tr><td>vindicated</td><td>"When Constance\'s stubbornness turned out to be exactly what saved them, Kate finally felt vindicated in trusting her all along." (clue: contextual/restating)</td></tr>' +
            '<tr><td>resolution</td><td>"The final chapter brought resolution to every storyline — each family reunited, each secret finally explained." (clue: comma-definition)</td></tr>' +
            '<tr><td>credible</td><td>"Mr. Benedict\'s claims about Mr. Curtain finally became credible, believable enough that officials were willing to act." (clue: comma-definition/restating)</td></tr>' +
            '</table>' },
          { id: 'v5b', label: 'Which Clue Told You the Meaning?', type: 'reflection',
            prompt: 'Pick at least two of this week\'s words (resourcefulness, futile, vindicated, resolution, credible) and explain what specific part of the sentence gave away its meaning. Point to the actual words that tipped you off, not just a definition.' }
        ]
      },
      grammar: {
        name: 'Grammar', tag: 'MCT-Based · Month 1, Week 5 Review',
        tasks: [
          { id: 'g5a', label: 'Level 1 — Tag the Parts of Speech', type: 'pos-tagger',
            sentence: ['While', 'the', 'professor', 'grew', 'nervous,', 'Nugget,', 'the', 'tiniest', 'hamster,', 'wrecked', 'the', 'entire', 'display', 'before', 'lunch.'],
            answers: ['Conjunction', 'Adjective', 'Noun', 'Verb', 'Adjective', 'Noun', 'Adjective', 'Adjective', 'Noun', 'Verb', 'Adjective', 'Adjective', 'Noun', 'Preposition', 'Noun'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.pos,
            explanations: [
              '"While" introduces the dependent clause and connects it to the main clause — that\'s a conjunction\'s job.',
              'Articles (a, an, the) are treated as adjectives — they modify the noun that follows.',
              'It names a thing — nouns name people, places, things, or ideas.',
              'It shows what the subject "professor" is described as. We\'ll classify it as action or linking specifically in Level 2.',
              'It describes "professor" — adjectives describe nouns.',
              'It names a specific individual — a proper noun.',
              'Article.',
              'It describes "hamster," comparing degree — "tiniest" is a superlative adjective.',
              'It names an animal — a renamed identity for Nugget.',
              'It shows the action the subject performed.',
              'Article.',
              'It describes "display" — adjectives describe nouns.',
              'It names a thing — the object of the action.',
              'It introduces a phrase showing where something happened, connecting to its object, "lunch."',
              'It names a thing — the object of the preposition "before."'
            ] },
          { id: 'g5b', label: 'Level 2 — Tag the Parts of the Sentence', type: 'phrase-tagger',
            sentence: ['While', 'the', 'professor', 'grew', 'nervous,', 'Nugget,', 'the', 'tiniest', 'hamster,', 'wrecked', 'the', 'entire', 'display', 'before', 'lunch.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.sentence,
            phrases: [
              { start: 2, end: 2, type: 'Subject', explanation: '"Professor" is who/what the dependent clause is about.' },
              { start: 3, end: 3, type: 'Linking Verb Predicate', explanation: '"Grew" doesn\'t show an action — it links "professor" to a description. That makes it a linking verb predicate, not an action verb predicate.' },
              { start: 4, end: 4, type: 'Subject Complement', explanation: '"Nervous" describes the subject "professor" after the linking verb "grew" — that\'s exactly what a subject complement does.' },
              { start: 5, end: 5, type: 'Subject', explanation: '"Nugget" is who the main clause is about — the one doing the action.' },
              { start: 9, end: 9, type: 'Action Verb Predicate', explanation: '"Wrecked" shows a real action Nugget performed, and it takes a direct object — only action verbs can do that.' },
              { start: 10, end: 12, type: 'Direct Object', explanation: '"The entire display" is what got wrecked — the direct object answers "what."' }
            ] },
          { id: 'g5c', label: 'Level 3 — Mark the Phrases', type: 'phrase-tagger',
            sentence: ['While', 'the', 'professor', 'grew', 'nervous,', 'Nugget,', 'the', 'tiniest', 'hamster,', 'wrecked', 'the', 'entire', 'display', 'before', 'lunch.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.phrase,
            phrases: [
              { start: 6, end: 8, type: 'Appositive', explanation: 'It renames "Nugget" — telling you who Nugget is, not where or when anything happened, which is what makes it an appositive instead of prepositional.' },
              { start: 13, end: 14, type: 'Prepositional', explanation: 'It starts with the preposition "before" and ends with its object "lunch" — that\'s the exact shape of a prepositional phrase.' }
            ] },
          { id: 'g5d', label: 'Level 4 — Mark the Clauses', type: 'phrase-tagger',
            sentence: ['While', 'the', 'professor', 'grew', 'nervous,', 'Nugget,', 'the', 'tiniest', 'hamster,', 'wrecked', 'the', 'entire', 'display', 'before', 'lunch.'],
            options: GRAMMAR_LEVEL_OPTIONS_SEED.clause,
            phrases: [
              { start: 0, end: 4, type: 'Dependent Clause', explanation: 'It starts with the subordinating conjunction "while" and can\'t stand alone as a complete sentence — that makes it dependent.' },
              { start: 5, end: 14, type: 'Independent Clause', explanation: 'It has its own subject and predicate ("Nugget... wrecked...") and could stand alone as a complete sentence — that makes it independent.' }
            ] },
          { id: 'g5e', label: 'Level 4 — Classify the Sentence Structure', type: 'graded-mc',
            questions: [
              { q: '"While the professor grew nervous, Nugget, the tiniest hamster, wrecked the entire display before lunch." — one independent clause plus one dependent clause makes this sentence:', options: GRAMMAR_LEVEL_OPTIONS_SEED.structure, correct: 2,
                explanation: 'One independent clause + one dependent clause = complex. (Simple = one independent clause alone. Compound = two or more independent clauses joined. Compound-complex = two+ independent clauses plus at least one dependent clause.)' }
            ] }
        ]
      },
      spelling: {
        name: 'Spelling', tag: 'AAS Level 7 · Step 11',
        tasks: [
          { id: 's5a', label: "This Week's Focus", type: 'read', content:
            '<div class="lesson-text"><p><b>Step 11 — The E-Consonant-E Pattern.</b> Some words end with a single consonant sandwiched between two e’s — persevere, extreme, adhere, supreme, interfere, precede, concrete, athlete. Once you notice that e-consonant-e "shape" at the end of a word, it’s much easier to spell correctly instead of guessing at the vowel sounds.</p><p>Completely and sincerely are built from the athlete-family and sincere-family words plus the -ly suffix, using that same ending pattern.</p></div>' },
          { id: 's5b', label: 'Word Cards 91–100 dictation', type: 'graded-dictation',
            prompt: 'Tap ▶ to hear each word — no text shown, same as Mom reading from the card.',
            words: [
              { answer: 'persevere', kind: 'word' }, { answer: 'extreme', kind: 'word' }, { answer: 'adhere', kind: 'word' },
              { answer: 'supreme', kind: 'word' }, { answer: 'interfere', kind: 'word' }, { answer: 'precede', kind: 'word' },
              { answer: 'concrete', kind: 'word' }, { answer: 'completely', kind: 'word' }, { answer: 'athlete', kind: 'word' }, { answer: 'sincerely', kind: 'word' }
            ] },
          { id: 's5c', label: 'Dictated sentences', type: 'graded-dictation',
            prompt: "All 10 sentences from this week's Reinforcement section.",
            words: [
              { answer: "I'll try not to interfere with your treasure hunt.", kind: 'sentence' },
              { answer: 'I know the mountain is high, but we must persevere!', kind: 'sentence' },
              { answer: 'We painted the piano completely purple.', kind: 'sentence' },
              { answer: 'The athlete rubbed his knees and ankles after the race.', kind: 'sentence' },
              { answer: 'How did you manage to adhere the fabric to your thumb?', kind: 'sentence' },
              { answer: 'A song or two will precede the speech on the history of pickles.', kind: 'sentence' },
              { answer: "The cat thinks she's the supreme ruler of the living room.", kind: 'sentence' },
              { answer: 'It took extreme measures to stuff his toys into that suitcase.', kind: 'sentence' },
              { answer: 'I wish there were more flowers and less concrete in the world.', kind: 'sentence' },
              { answer: 'The sobbing sisters were sincerely sad.', kind: 'sentence' }
            ] }
        ]
      },
      reading: {
        name: 'Reading', tag: 'The Mysterious Benedict Society · Ch. 33–39 (Finale)',
        tasks: [
          { id: 'r5a', label: 'This Week’s Reading: Chapters 33–39 (Finishing the Book!)', type: 'read', content:
            '<div class="lesson-text"><p><b>As you read, watch for:</b></p><p>1. Kate and Constance’s escape from the tower. Notice a choice Kate makes about teamwork instead of going it alone — it echoes something Mr. Benedict told her earlier in the book.</p><p>2. The moment Reynie tries to trick the Whisperer machine itself. Notice <i>why</i> it doesn’t work — that failure tells you something important about honesty as a theme in this book.</p><p>3. The climax, where the team’s whole plan comes down to Constance specifically. Think back over everything you’ve noticed about her since Chapter 1.</p><p>4. The final chapter ties up a lot of loose ends — families reunited, secrets explained. Watch especially for one surprising reveal about Constance herself.</p></div>' },
          { id: 'r5b', label: 'Capstone — POV Payoff', type: 'reflection',
            prompt: "Because we've been locked in Reynie's POV the entire book, there's a surprise about Constance we only learn at the very end, right alongside him. What was your reaction when you found out the truth about her? Does it change how you feel about any of her stubborn or difficult moments earlier in the book?" },
          { id: 'r5c', label: 'Capstone — Plot Structure Synthesis', type: 'reflection',
            prompt: "Look back at how Constance is introduced early in the book versus how she matters in the climax. What small clues, if any, do you remember noticing along the way that the ending pays off? (If you don't remember any — that's honest too. It just means the author hid it well.)" },
          { id: 'r5d', label: 'Capstone — Wrap-Up', type: 'reflection',
            prompt: "Now that you've read the whole book: was 'Plot Structure & POV' a good lens for understanding this particular story? What's one thing you noticed this month that you wouldn't have thought about if you'd just read for plot?" }
        ]
      },
      writing: {
        name: 'Writing', tag: 'MCT Essay Voyage (adapted) · Block 1',
        tasks: [
          { id: 'w5a', label: 'Final Draft', type: 'reflection',
            prompt: 'Paste your final, clean two-paragraph argument here — the polished version of what you’ve been drafting and revising all month.' },
          { id: 'w5b', label: 'Capstone Reflection', type: 'reflection',
            prompt: 'At the start of this month, you learned that a lot of "evidence" people use is really just a repeated opinion. Find one sentence in your own first draft that would have failed that test a month ago — what did you change, and why does the new version actually work as evidence?' }
        ]
      }
    }
  }
];
